graph TD
  qa --> gitlab-read
  qa --> vault-read
  qa --> nexus-read
  qa --> grafana-read
  support --> zabbix-read
  support --> grafana-read
  support --> netdata-read
  dev --> gitlab-write
  dev --> vault-read
  dev --> nexus-write
  infra-admin --> ubuntu-admin
  infra-admin --> centos-admin
  ci-admin --> gitlab-admin
  ci-admin --> nexus-admin
  release-manager --> gitlab-admin
  release-manager --> vault-read
  release-manager --> nexus-admin
  readonly --> gitlab-read
  readonly --> vault-read
  readonly --> grafana-read
  readonly --> zabbix-read
  readonly --> netdata-read
  readonly --> nexus-read
  teamlead-dev --> gitlab-write
  teamlead-dev --> gitlab-admin
  teamlead-dev --> vault-read
  teamlead-dev --> vault-write
  teamlead-dev --> nexus-write
  teamlead-dev --> grafana-read
  vault-access --> vault-read
  vault-access --> vault-write